/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.srini.avro.types;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeliveryAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5754784370948085335L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryAddress\",\"namespace\":\"com.srini.avro.types\",\"fields\":[{\"name\":\"addressLine\",\"type\":[\"null\",\"string\"]},{\"name\":\"city\",\"type\":[\"null\",\"string\"]},{\"name\":\"state\",\"type\":[\"null\",\"string\"]},{\"name\":\"pinCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"contactNumber\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeliveryAddress> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeliveryAddress> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeliveryAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeliveryAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeliveryAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeliveryAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeliveryAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeliveryAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeliveryAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence addressLine;
  private java.lang.CharSequence city;
  private java.lang.CharSequence state;
  private java.lang.CharSequence pinCode;
  private java.lang.CharSequence contactNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeliveryAddress() {}

  /**
   * All-args constructor.
   * @param addressLine The new value for addressLine
   * @param city The new value for city
   * @param state The new value for state
   * @param pinCode The new value for pinCode
   * @param contactNumber The new value for contactNumber
   */
  public DeliveryAddress(java.lang.CharSequence addressLine, java.lang.CharSequence city, java.lang.CharSequence state, java.lang.CharSequence pinCode, java.lang.CharSequence contactNumber) {
    this.addressLine = addressLine;
    this.city = city;
    this.state = state;
    this.pinCode = pinCode;
    this.contactNumber = contactNumber;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return addressLine;
    case 1: return city;
    case 2: return state;
    case 3: return pinCode;
    case 4: return contactNumber;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: addressLine = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.CharSequence)value$; break;
    case 3: pinCode = (java.lang.CharSequence)value$; break;
    case 4: contactNumber = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'addressLine' field.
   * @return The value of the 'addressLine' field.
   */
  public java.lang.CharSequence getAddressLine() {
    return addressLine;
  }


  /**
   * Sets the value of the 'addressLine' field.
   * @param value the value to set.
   */
  public void setAddressLine(java.lang.CharSequence value) {
    this.addressLine = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'pinCode' field.
   * @return The value of the 'pinCode' field.
   */
  public java.lang.CharSequence getPinCode() {
    return pinCode;
  }


  /**
   * Sets the value of the 'pinCode' field.
   * @param value the value to set.
   */
  public void setPinCode(java.lang.CharSequence value) {
    this.pinCode = value;
  }

  /**
   * Gets the value of the 'contactNumber' field.
   * @return The value of the 'contactNumber' field.
   */
  public java.lang.CharSequence getContactNumber() {
    return contactNumber;
  }


  /**
   * Sets the value of the 'contactNumber' field.
   * @param value the value to set.
   */
  public void setContactNumber(java.lang.CharSequence value) {
    this.contactNumber = value;
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.srini.avro.types.DeliveryAddress.Builder newBuilder() {
    return new com.srini.avro.types.DeliveryAddress.Builder();
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.srini.avro.types.DeliveryAddress.Builder newBuilder(com.srini.avro.types.DeliveryAddress.Builder other) {
    if (other == null) {
      return new com.srini.avro.types.DeliveryAddress.Builder();
    } else {
      return new com.srini.avro.types.DeliveryAddress.Builder(other);
    }
  }

  /**
   * Creates a new DeliveryAddress RecordBuilder by copying an existing DeliveryAddress instance.
   * @param other The existing instance to copy.
   * @return A new DeliveryAddress RecordBuilder
   */
  public static com.srini.avro.types.DeliveryAddress.Builder newBuilder(com.srini.avro.types.DeliveryAddress other) {
    if (other == null) {
      return new com.srini.avro.types.DeliveryAddress.Builder();
    } else {
      return new com.srini.avro.types.DeliveryAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeliveryAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryAddress>
    implements org.apache.avro.data.RecordBuilder<DeliveryAddress> {

    private java.lang.CharSequence addressLine;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state;
    private java.lang.CharSequence pinCode;
    private java.lang.CharSequence contactNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.srini.avro.types.DeliveryAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.addressLine)) {
        this.addressLine = data().deepCopy(fields()[0].schema(), other.addressLine);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.pinCode)) {
        this.pinCode = data().deepCopy(fields()[3].schema(), other.pinCode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.contactNumber)) {
        this.contactNumber = data().deepCopy(fields()[4].schema(), other.contactNumber);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing DeliveryAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(com.srini.avro.types.DeliveryAddress other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.addressLine)) {
        this.addressLine = data().deepCopy(fields()[0].schema(), other.addressLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pinCode)) {
        this.pinCode = data().deepCopy(fields()[3].schema(), other.pinCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contactNumber)) {
        this.contactNumber = data().deepCopy(fields()[4].schema(), other.contactNumber);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'addressLine' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine() {
      return addressLine;
    }


    /**
      * Sets the value of the 'addressLine' field.
      * @param value The value of 'addressLine'.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder setAddressLine(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.addressLine = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'addressLine' field has been set.
      * @return True if the 'addressLine' field has been set, false otherwise.
      */
    public boolean hasAddressLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'addressLine' field.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder clearAddressLine() {
      addressLine = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder setState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'pinCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPinCode() {
      return pinCode;
    }


    /**
      * Sets the value of the 'pinCode' field.
      * @param value The value of 'pinCode'.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder setPinCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.pinCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'pinCode' field has been set.
      * @return True if the 'pinCode' field has been set, false otherwise.
      */
    public boolean hasPinCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'pinCode' field.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder clearPinCode() {
      pinCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'contactNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getContactNumber() {
      return contactNumber;
    }


    /**
      * Sets the value of the 'contactNumber' field.
      * @param value The value of 'contactNumber'.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder setContactNumber(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.contactNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'contactNumber' field has been set.
      * @return True if the 'contactNumber' field has been set, false otherwise.
      */
    public boolean hasContactNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'contactNumber' field.
      * @return This builder.
      */
    public com.srini.avro.types.DeliveryAddress.Builder clearContactNumber() {
      contactNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeliveryAddress build() {
      try {
        DeliveryAddress record = new DeliveryAddress();
        record.addressLine = fieldSetFlags()[0] ? this.addressLine : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.pinCode = fieldSetFlags()[3] ? this.pinCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.contactNumber = fieldSetFlags()[4] ? this.contactNumber : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeliveryAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeliveryAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeliveryAddress>
    READER$ = (org.apache.avro.io.DatumReader<DeliveryAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.addressLine == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.addressLine);
    }

    if (this.city == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.city);
    }

    if (this.state == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.state);
    }

    if (this.pinCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.pinCode);
    }

    if (this.contactNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.contactNumber);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.addressLine = null;
      } else {
        this.addressLine = in.readString(this.addressLine instanceof Utf8 ? (Utf8)this.addressLine : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.city = null;
      } else {
        this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.state = null;
      } else {
        this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.pinCode = null;
      } else {
        this.pinCode = in.readString(this.pinCode instanceof Utf8 ? (Utf8)this.pinCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.contactNumber = null;
      } else {
        this.contactNumber = in.readString(this.contactNumber instanceof Utf8 ? (Utf8)this.contactNumber : null);
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.addressLine = null;
          } else {
            this.addressLine = in.readString(this.addressLine instanceof Utf8 ? (Utf8)this.addressLine : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.city = null;
          } else {
            this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.state = null;
          } else {
            this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.pinCode = null;
          } else {
            this.pinCode = in.readString(this.pinCode instanceof Utf8 ? (Utf8)this.pinCode : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.contactNumber = null;
          } else {
            this.contactNumber = in.readString(this.contactNumber instanceof Utf8 ? (Utf8)this.contactNumber : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










